services:
  newsnow:
    image: ghcr.io/ourongxing/newsnow:latest
    container_name: newsnow
    ports:
      - '4444:4444'
    volumes:
      - newsnow_data:/usr/app/.data
    environment:
      - HOST=0.0.0.0
      - PORT=4444
      - NODE_ENV=production
      - G_CLIENT_ID=Ov23li7NCUxx2YLgtix7
      - G_CLIENT_SECRET=1af4768be3b3421b68e8cde85b23b8f124481b33
      - JWT_SECRET=1af4768be3b3421b68e8cde85b23b8f124481b33
      - INIT_TABLE=true
      - ENABLE_CACHE=true

volumes:
  newsnow_data:
    name: newsnow_data
